### ISSUE TITLE
cwl-runner output directory not found error

### ISSUE THREAD

**Issue by JenHauen16** [jorvis/GALES#14]
Even with full paths, I cannot get past the cwl-runner output directory not found.

The output directory does contain these files:
jenha@DESKTOP-NJHO60U ~/GALES/GALES/bin/output
$ ls prok-annotation-cheetah.cwl  prok-annotation-cheetah.json

jenha@DESKTOP-NJHO60U ~/GALES/GALES/bin
$ ls
Darwin download_reference_data GCA_002420305.1_ASM242030v1_genomic.fna launch_interactive list_gce_bucket.py prok-annotation-cheetah.cwl report_stats.py view_annotation
dbs filter_blast_ev_db_by_accessions.py generate_pipeline_list.py Linux output prok-annotation-cheetah.json run_prok_pipeline

jenha@DESKTOP-NJHO60U ~/GALES/GALES/bin
$ /home/jenha/GALES/GALES/bin/run_prok_pipeline -i /home/jenha/GALES/GALES/bin/GCA_002420305.1_ASM242030v1_genomic.fna -od /home/jenha/GALES/GALES/bin/output/ -v cheetah -rd /home/jenha/GALES/GALES/bin/dbs/
Starting pipeline. If this is your first time running this pipeline there will be some latency as the necessary Docker images are downloaded. This is a one-time cost.
Running command: cwl-runner --outdir /home/jenha/GALES/GALES/bin/output /home/jenha/GALES/GALES/bin/output/prok-annotation-cheetah.cwl /home/jenha/GALES/GALES/bin/output/prok-annotation-cheetah.json
C:\Users\jenha\AppData\Local\Programs\Python\Python36\Scripts\cwl-runner 1.0.20190228155703
Traceback (most recent call last):
File "c:\users\jenha\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\users\jenha\appdata\local\programs\python\python36\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\jenha\AppData\Local\Programs\Python\Python36\Scripts\cwl-runner.exe_main.py", line 9, in
File "c:\users\jenha\appdata\local\programs\python\python36\lib\site-packages\cwltool\main.py", line 632, in main
fetcher_constructor=loadingContext.fetcher_constructor)
File "c:\users\jenha\appdata\local\programs\python\python36\lib\site-packages\cwltool\load_tool.py", line 89, in resolve_tool_uri
raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.validate.ValidationException: Not found: '/home/jenha/GALES/GALES/bin/output/prok-annotation-cheetah.cwl'
ERROR: Return code 1 when running the following command: cwl-runner --outdir /home/jenha/GALES/GALES/bin/output /home/jenha/GALES/GALES/bin/output/prok-annotation-cheetah.cwl /home/jenha/GALES/GALES/bin/output/prok-annotation-cheetah.json

**Comment by jorvis** [comment]
Ok, after you get that error can you post the result of this?

ls -l /home/jenha/GALES/GALES/bin/output

**Comment by JenHauen16** [comment]
$ ls -l /home/jenha/GALES/GALES/bin/output
total 16
-rw-r--r-- 1 jenha jenha 8472 Apr 21 17:48 prok-annotation-cheetah.cwl
-rw-r--r-- 1 jenha jenha 3377 Apr 21 17:48 prok-annotation-cheetah.json

**Comment by jorvis** [comment]
Would you mind giving information about your system (Linux, OSX, etc.) and compress and attach the input file you were trying to run?

**Comment by JenHauen16** [comment]
The above code was run on Windows 10 with the Cygwin emulator. 

I redid everything on a Ubuntu VM and now get the following errors.
jen@jen-VirtualBox:~/GALES/bin$ ./run_prok_pipeline -i ~/GALES/bin/GCA_001580535.1_ASM158053v1_genomic.fna -od ~/GALES/bin/ouput -v cheetah -rd dbs
Starting pipeline.  If this is your first time running this pipeline there will be some latency as the necessary Docker images are downloaded. This is a one-time cost.
Running command: cwl-runner --outdir /home/jen/GALES/bin/ouput /home/jen/GALES/bin/ouput/prok-annotation-cheetah.cwl /home/jen/GALES/bin/ouput/prok-annotation-cheetah.json
/usr/local/bin/cwl-runner 1.0.20190228155703
Resolved '/home/jen/GALES/bin/ouput/prok-annotation-cheetah.cwl' to 'file:///home/jen/GALES/bin/ouput/prok-annotation-cheetah.cwl'
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/json?filters=%7B%22reference%22%3A%7B%22node%3Aslim%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim
ERROR: Return code 1 when running the following command: cwl-runner --outdir /home/jen/GALES/bin/ouput /home/jen/GALES/bin/ouput/prok-annotation-cheetah.cwl /home/jen/GALES/bin/ouput/prok-annotation-cheetah.json


[GCA_001580535.1_ASM158053v1_genomic.fna.gz](https://github.com/jorvis/GALES/files/3103405/GCA_001580535.1_ASM158053v1_genomic.fna.gz)

**Comment by JenHauen16** [comment]
Ok, I got this all to work finally! Be sure to fully write out the paths from /home/..., create your vm with more space than 10 gb, make sure your user has docker permissions, and google all the errors...there are many solutions out there!

**Comment by jorvis** [comment]
Glad you finally got it!  Yes, successful setup of Docker is definitely a pre-req.

**Comment by SUN-Changyu** [comment]
> Ok, I got this all to work finally! Be sure to fully write out the paths from /home/..., create your vm with more space than 10 gb, make sure your user has docker permissions, and google all the errors...there are many solutions out there!

Hi, @JenHauen16 . I encountered the same issue with running cwl-runner on my ubuntu VM. And I've been working my brain out for it with zero progress. By any chance, you remember how you solved this problem? Many thanks.

**Comment by SUN-Changyu** [comment]
Solved the problem by installing docker for win10 and setting up the permission. If anyone gets this issue on WSL, please refer to this link and reinstall the docker from the beginning: https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4
