### ISSUE TITLE
unable to install biocode jinja2

### ISSUE THREAD

**Issue by mchovat** [jorvis/GALES#18]
I am using MacOS. I have tried installing biocode but I keep running into an error.  I have tried reinstalling igraph as well tried upgrading pip and changing permissions on the pip directory but I am still getting this error:

mchovat:dbs mrchovatia$ brew install igraph
Warning: igraph 0.7.1_6 is already installed and up-to-date
To reinstall 0.7.1_6, run `brew reinstall igraph`
mchovat:dbs mrchovatia$ brew reinstall igraph
==> Reinstalling igraph 
==> Downloading https://homebrew.bintray.com/bottles/igraph-0.7.1_6.mojave.bottle
Already downloaded: /Users/mrchovatia/Library/Caches/Homebrew/downloads/e3aec1eec2b22327a31b3962a83834156f140ee5c0a592845483304cd085c05f--igraph-0.7.1_6.mojave.bottle.tar.gz
==> Pouring igraph-0.7.1_6.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/igraph/0.7.1_6: 85 files, 6MB
mchovat:dbs mrchovatia$ sudo pip3 install biocode jinja2
The directory '/Users/mrchovatia/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/mrchovatia/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting biocode
  Downloading https://files.pythonhosted.org/packages/ac/58/b16f07e13b99403a0069b7782dc963882f634b6863d6e4bba85d327bd634/biocode-0.9.0.tar.gz (9.4MB)
    100% |████████████████████████████████| 9.4MB 839kB/s 
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2.10.1)
Collecting python-igraph (from biocode)
  Downloading https://files.pythonhosted.org/packages/0f/a0/4e7134f803737aa6eebb4e5250565ace0e2599659e22be7f7eba520ff017/python-igraph-0.7.1.post6.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 754kB/s 
Collecting matplotlib (from biocode)
  Downloading https://files.pythonhosted.org/packages/2e/81/bb51214944e79f9c9261badd7ef99b573fb0bc9110c0075c6a9e76224d0d/matplotlib-3.0.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.3MB)
    100% |████████████████████████████████| 14.3MB 560kB/s 
Collecting taxadb (from biocode)
  Downloading https://files.pythonhosted.org/packages/f8/be/19e605b91abc7c6e3c6a183d89f1f6dca2c2851ba588f9673e77302934bc/taxadb-0.9.0-py3-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jinja2) (1.1.1)
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->biocode) (2.8.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->biocode) (2.4.0)
Collecting cycler>=0.10 (from matplotlib->biocode)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->biocode)
  Downloading https://files.pythonhosted.org/packages/68/f2/21ec13269a420c063a3d7d8c87dac030da7b00fc6b27fa88cfb1c72a645b/kiwisolver-1.0.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (107kB)
    100% |████████████████████████████████| 112kB 568kB/s 
Collecting numpy>=1.10.0 (from matplotlib->biocode)
  Downloading https://files.pythonhosted.org/packages/43/6e/71a3af8680a159a141fab5b4d19988111a09c02ffbfdeb42175cca0fa341/numpy-1.16.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 808kB/s 
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from taxadb->biocode) (2.21.0)
Collecting peewee==2.8.1 (from taxadb->biocode)
  Downloading https://files.pythonhosted.org/packages/59/4a/a1b78b0e47e880c07da21d633ff2ac8d5edbf969049a414edfbdadaed869/peewee-2.8.1.tar.gz (474kB)
    100% |████████████████████████████████| 481kB 904kB/s 
Collecting tqdm (from taxadb->biocode)
  Downloading https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 778kB/s 
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from python-dateutil>=2.1->matplotlib->biocode) (1.12.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->biocode) (40.6.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->taxadb->biocode) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->taxadb->biocode) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->taxadb->biocode) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->taxadb->biocode) (1.24.2)
Installing collected packages: python-igraph, cycler, kiwisolver, numpy, matplotlib, peewee, tqdm, taxadb, biocode
  Running setup.py install for python-igraph ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-gcamzet7/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-up1h0e_a/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/configuration.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/clustering.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/compat.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/formula.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/layout.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/cut.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/matching.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/summary.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/datatypes.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/utils.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    copying igraph/statistics.py -> build/lib.macosx-10.9-x86_64-3.7/igraph
    creating build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/structural.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/colortests.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/attributes.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/rng.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/conversion.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/vertexseq.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/flow.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/games.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/matching.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/generators.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/isomorphism.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/basic.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/utils.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/edgeseq.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/decomposition.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/iterators.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/spectral.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/separators.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/homepage.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/atlas.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/indexing.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/operators.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/layouts.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/cliques.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/foreign.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    copying igraph/test/bipartite.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/test
    creating build/lib.macosx-10.9-x86_64-3.7/igraph/app
    copying igraph/app/shell.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/app
    copying igraph/app/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/app
    creating build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/shapes.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/edge.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/baseclasses.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/graph.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/coord.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/vertex.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/utils.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/text.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/metamagic.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    copying igraph/drawing/colors.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/drawing
    creating build/lib.macosx-10.9-x86_64-3.7/igraph/remote
    copying igraph/remote/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/remote
    copying igraph/remote/nexus.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/remote
    copying igraph/remote/gephi.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/remote
    creating build/lib.macosx-10.9-x86_64-3.7/igraph/vendor
    copying igraph/vendor/texttable.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/vendor
    copying igraph/vendor/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/igraph/vendor
    Fixing build/lib.macosx-10.9-x86_64-3.7/igraph/configuration.py build/lib.macosx-10.9-x86_64-3.7/igraph/clustering.py build/lib.macosx-10.9-x86_64-3.7/igraph/compat.py build/lib.macosx-10.9-x86_64-3.7/igraph/formula.py build/lib.macosx-10.9-x86_64-3.7/igraph/layout.py build/lib.macosx-10.9-x86_64-3.7/igraph/cut.py build/lib.macosx-10.9-x86_64-3.7/igraph/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/matching.py build/lib.macosx-10.9-x86_64-3.7/igraph/summary.py build/lib.macosx-10.9-x86_64-3.7/igraph/datatypes.py build/lib.macosx-10.9-x86_64-3.7/igraph/utils.py build/lib.macosx-10.9-x86_64-3.7/igraph/statistics.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/structural.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/colortests.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/attributes.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/rng.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/conversion.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/vertexseq.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/flow.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/games.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/matching.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/generators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/isomorphism.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/basic.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/utils.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/edgeseq.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/decomposition.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/iterators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/spectral.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/separators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/homepage.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/atlas.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/indexing.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/operators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/layouts.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/cliques.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/foreign.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/bipartite.py build/lib.macosx-10.9-x86_64-3.7/igraph/app/shell.py build/lib.macosx-10.9-x86_64-3.7/igraph/app/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/shapes.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/edge.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/baseclasses.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/graph.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/coord.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/vertex.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/utils.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/text.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/metamagic.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/colors.py build/lib.macosx-10.9-x86_64-3.7/igraph/remote/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/remote/nexus.py build/lib.macosx-10.9-x86_64-3.7/igraph/remote/gephi.py build/lib.macosx-10.9-x86_64-3.7/igraph/vendor/texttable.py build/lib.macosx-10.9-x86_64-3.7/igraph/vendor/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib.macosx-10.9-x86_64-3.7/igraph/configuration.py build/lib.macosx-10.9-x86_64-3.7/igraph/clustering.py build/lib.macosx-10.9-x86_64-3.7/igraph/compat.py build/lib.macosx-10.9-x86_64-3.7/igraph/formula.py build/lib.macosx-10.9-x86_64-3.7/igraph/layout.py build/lib.macosx-10.9-x86_64-3.7/igraph/cut.py build/lib.macosx-10.9-x86_64-3.7/igraph/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/matching.py build/lib.macosx-10.9-x86_64-3.7/igraph/summary.py build/lib.macosx-10.9-x86_64-3.7/igraph/datatypes.py build/lib.macosx-10.9-x86_64-3.7/igraph/utils.py build/lib.macosx-10.9-x86_64-3.7/igraph/statistics.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/structural.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/colortests.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/attributes.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/rng.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/conversion.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/vertexseq.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/flow.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/games.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/matching.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/generators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/isomorphism.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/basic.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/utils.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/edgeseq.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/decomposition.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/iterators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/spectral.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/separators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/homepage.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/atlas.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/indexing.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/operators.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/layouts.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/cliques.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/foreign.py build/lib.macosx-10.9-x86_64-3.7/igraph/test/bipartite.py build/lib.macosx-10.9-x86_64-3.7/igraph/app/shell.py build/lib.macosx-10.9-x86_64-3.7/igraph/app/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/shapes.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/edge.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/baseclasses.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/graph.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/coord.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/vertex.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/utils.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/text.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/metamagic.py build/lib.macosx-10.9-x86_64-3.7/igraph/drawing/colors.py build/lib.macosx-10.9-x86_64-3.7/igraph/remote/__init__.py build/lib.macosx-10.9-x86_64-3.7/igraph/remote/nexus.py build/lib.macosx-10.9-x86_64-3.7/igraph/remote/gephi.py build/lib.macosx-10.9-x86_64-3.7/igraph/vendor/texttable.py build/lib.macosx-10.9-x86_64-3.7/igraph/vendor/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    
    Version 0.7.1.post6 of the C core of igraph is not found among the nightly builds.
    Use the --c-core-version switch to try a different version.
    
    Could not download and compile the C core of igraph.
    
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-gcamzet7/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-up1h0e_a/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-gcamzet7/python-igraph/
You are using pip version 18.1, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by jorvis** [comment]
This appears to be relevant.  Could you try their suggestions?

https://github.com/igraph/python-igraph/issues/159

**Comment by mchovat** [comment]
I tried these commands:
brew install igraph
pip -v install python-igraph==0.7.1.post6

and got this error:
InstallationError: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/9d/63m3z36x70x86vrgpgpb_tnc0000gr/T/pip-install-8sFM5i/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/9d/63m3z36x70x86vrgpgpb_tnc0000gr/T/pip-record-N6cfEl/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/9d/63m3z36x70x86vrgpgpb_tnc0000gr/T/pip-install-8sFM5i/python-igraph/

Then I tried this command:
sudo apt install build-essential python-dev libxml2 libxml2-dev zlib1g-dev

But then I got this:
No Java runtime present, requesting install.
I clicked OK and nothing happened.

**Comment by jorvis** [comment]
I'm afraid I don't have an OS X machine to test here.  You'll need to search a bit about installing python-igraph on OS X.  I found this from the source:

https://igraph.org/python/#pyinstallosx

**Comment by mchovat** [comment]
Ok thank you! I will try to look into this a bit more.  Will post if something does end up working.

**Comment by jianlanren** [comment]
I have the same problem on my MacOS X. Please let me know if you get any solutions.

**Comment by jianlanren** [comment]
I tried uninstall jinja2 first and then re-install. 
$ pip uninstall jinja2
$ sudo pip install jinja2
It works for me and lets me go to the running step.

**Comment by mchovat** [comment]
Thank you. I did try that but it still doesn't work for me.  I can't install Biocode.

**Comment by jorvis** [comment]
In case anyone reads this later, this came up again on a new laptop and doing this command first fixed it:

$ sudo apt install bison flex
