### ISSUE TITLE
Running Command Error

### ISSUE THREAD

**Issue by jianlanren** [jorvis/GALES#19]
I am using MacOS, and finally got everything works before the running command.

ERRO[0000] error waiting for container: context canceled 
[job rapsearch2] Max memory used: 0MiB
[job rapsearch2] Job error:
Error collecting output for parameter 'output_base':

Final process status is permanentFail
ERROR: Return code 1 when running the following command: cwl-runner --outdir /tmp/demo /tmp/demo/prok-annotation-cheetah.cwl /tmp/demo/prok-annotation-cheetah.json
[Running Error.txt](https://github.com/jorvis/GALES/files/3115032/Running.Error.txt)

Whole error attached below.

**Comment by jorvis** [comment]
This seems to be the relevant portion from the logs.  OS X seems to require you to do more for the mount needed to work:

```
docker: Error response from daemon: Mounts denied: \
The paths /dbs/uniprot_sprot_all_and_trembl_characterized.20180904.rapsearch2.db.info and /dbs/uniprot_sprot_all_and_trembl_characterized.20180904.rapsearch2.db\
are not shared from OS X and are not known to Docker.\
You can configure shared paths from Docker -> Preferences... -> File Sharing.\
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\
```
