### ISSUE TITLE
linux install

### ISSUE THREAD

**Issue by rsc3** [jorvis/GALES#30]
sudo apt-get install docker.io python3 python3-pip python-pip zlib1g-dev libxml2-dev
[sudo] password for cox: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pip

**Comment by jorvis** [comment]
Can you specify which OS and version you are using?  If Ubuntu (and it seems like it is) be sure you have the Universe repository enabled:

https://linuxconfig.org/how-to-enable-disable-universe-multiverse-and-restricted-repository-on-ubuntu-20-04-lts-focal-fossa

Please reopen if that doesn't fix it.
