### ISSUE TITLE
Image platform specific to amd64

### ISSUE THREAD

**Issue by jeffreykstone** [jorvis/GALES#34]
I have an apple silicon Mac and so am getting the following:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by jorvis** [comment]
Just a warning.  Does it run through completion anyway?  Others reported yes.

**Comment by jeffreykstone** [comment]
Not for me for whatever reason. I left specific comments when I submitted what did come through.

**Comment by Meganmli** [comment]
After running `./run_prok_pipeline -i ../test_data/genomes/E_coli_k12_dh10b.fna -od /tmp/demo -v cheetah -rd dbs` I get this same error message and my terminal seems to hang indefinitely.

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_filebuf::underflow error reading the file: iostream error`

**Comment by jorvis** [comment]
What do you see in another terminal if you run 'top' or anything to watch your system  resources?  Are the computes still running?

**Comment by Meganmli** [comment]
@jorvis I see kernel_task, WindowServer, JavaApplicat, and top running

**Comment by Meganmli** [comment]
Update: running the previous command as seen below with full paths successfully comleted!
`./run_prok_pipeline -i {full/path/to}/test_data/genomes/E_coli_k12_dh10b.fna -od /tmp/demo -v cheetah -rd {full/path/to}/dbs -t 3`

Can resolve this issue

**Comment by jorvis** [comment]
Confirmed, the rest are just warnings.
