### ISSUE TITLE
Final process status is permanentFail

### ISSUE THREAD

**Issue by lengjing0519** [jorvis/GALES#36]
When I run the running command like this on Mac: 
`./run_prok_pipeline -i /Users/lengjing/Desktop/712/HW12/GALES_project/GCF_000005845.2_ASM584v2_genomic.fna  -od /tmp/demo -v cheetah -rd dbs -t 4`
The output is as below:
```
Starting pipeline.  If this is your first time running this pipeline there will be some latency as the necessary Docker images are downloaded. This is a one-time cost.
Running command: cwl-runner --outdir /tmp/demo /tmp/demo/prok-annotation-cheetah.cwl /tmp/demo/prok-annotation-cheetah.json
INFO /Users/lengjing/anaconda3/bin/cwl-runner 3.1.20240404144621
INFO Resolved '/tmp/demo/prok-annotation-cheetah.cwl' to 'file:///tmp/demo/prok-annotation-cheetah.cwl'

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview docker.io/node:alpine
INFO [workflow ] start
INFO [workflow ] starting step prodigal
INFO [step prodigal] start
INFO [job prodigal] /private/tmp/docker_tmpuhy17gg8$ docker \
    run \
    -i \
    --mount=type=bind,source=/private/tmp/docker_tmpuhy17gg8,target=/sdmbCI \
    --mount=type=bind,source=/private/tmp/docker_tmp32f30v8w,target=/tmp \
    --mount=type=bind,source=/Users/lengjing/Desktop/712/HW12/GALES_project/GCF_000005845.2_ASM584v2_genomic.fna,target=/var/lib/cwl/stga7c3fdc0-c221-4638-87a7-355c541f8038/GCF_000005845.2_ASM584v2_genomic.fna,readonly \
    --workdir=/sdmbCI \
    --read-only=true \
    --user=501:20 \
    --rm \
    --cidfile=/private/tmp/docker_tmpeu4k361s/20240418084933-250417.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/sdmbCI \
    jorvis/gales-gce \
    prodigal \
    -i \
    /var/lib/cwl/stga7c3fdc0-c221-4638-87a7-355c541f8038/GCF_000005845.2_ASM584v2_genomic.fna \
    -f \
    gff \
    -o \
    prodigal.annotation.gff \
    -a \
    prodigal.annotation.faa
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...4641652 bp seq created, 50.79 pct GC
Locating all potential starts and stops...240856 nodes
Looking for GC bias in different frames...frame bias scores: 1.56 0.18 1.26
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...done!
-------------------------------------
Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (4641652 bp)...done!
INFO [job prodigal] Max memory used: 411MiB
INFO [job prodigal] completed success
INFO [step prodigal] completed success
INFO [workflow ] starting step barrnap
INFO [step barrnap] start
INFO [job barrnap] /private/tmp/docker_tmpa_2uvu8p$ docker \
    run \
    -i \
    --mount=type=bind,source=/private/tmp/docker_tmpa_2uvu8p,target=/sdmbCI \
    --mount=type=bind,source=/private/tmp/docker_tmphwl816u5,target=/tmp \
    --mount=type=bind,source=/Users/lengjing/Desktop/712/HW12/GALES_project/GCF_000005845.2_ASM584v2_genomic.fna,target=/var/lib/cwl/stgfc69e62a-a419-4902-92db-5e779e7e0da7/GCF_000005845.2_ASM584v2_genomic.fna,readonly \
    --workdir=/sdmbCI \
    --read-only=true \
    --log-driver=none \
    --user=501:20 \
    --rm \
    --cidfile=/private/tmp/docker_tmp2mrddk7f/20240418085010-990529.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/sdmbCI \
    jorvis/gales-gce \
    barrnap \
    /var/lib/cwl/stgfc69e62a-a419-4902-92db-5e779e7e0da7/GCF_000005845.2_ASM584v2_genomic.fna > /private/tmp/docker_tmpa_2uvu8p/barnapp.gff
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[12:50:11] This is barrnap 0.7
[12:50:11] Written by Torsten Seemann <torsten.seemann@gmail.com>
[12:50:11] Obtained from https://github.com/Victorian-Bioinformatics-Consortium/barrnap
[12:50:11] Detected operating system: linux
[12:50:11] Using HMMER binary: /opt/barrnap/bin/../binaries/linux/nhmmer
[12:50:11] Will use 8 threads
[12:50:11] Setting evalue cutoff to 1e-06
[12:50:11] Will tag genes  < 0.8 of expected length.
[12:50:11] Will reject genes < 0.5 of expected length.
[12:50:11] Using database: /opt/barrnap/bin/../db/bac.hmm
[12:50:11] Usage: barrnap <file.fasta>
WARNING [job barrnap] exited with status: 2
WARNING [job barrnap] completed permanentFail
WARNING [step barrnap] completed permanentFail
INFO [workflow ] completed permanentFail
{
    "fasta_files": null,
    "barrnap_gff_output": {
        "location": "file:///tmp/demo/barnapp.gff",
        "basename": "barnapp.gff",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "path": "/tmp/demo/barnapp.gff"
    },
    "aragorn_raw_output": null,
    "prodigal_annot_file": {
        "location": "file:///tmp/demo/prodigal.annotation.gff",
        "basename": "prodigal.annotation.gff",
        "class": "File",
        "checksum": "sha1$f55d86eab3f004ededacb8d8a0e6f83bfe3c530d",
        "size": 1000054,
        "path": "/tmp/demo/prodigal.annotation.gff"
    },
    "prodigal_protein_file": {
        "location": "file:///tmp/demo/prodigal.annotation.faa",
        "basename": "prodigal.annotation.faa",
        "class": "File",
        "checksum": "sha1$8270e962cb3b5236d84199411127ed8d52d6a7cc",
        "size": 1943518,
        "path": "/tmp/demo/prodigal.annotation.faa"
    },
    "prodigal_gff3": null,
    "prodigal_protein_fasta": null,
    "rapsearch2_m8_files": null,
    "hmmscan_raw_files": null,
    "hmmscan_htab_files": null,
    "tmhmm_raw_files": null,
    "attributor_files": null,
    "attributor_output_config": null,
    "merged_gff3": null
}WARNING Final process status is permanentFail
ERROR: Return code 1 when running the following command: cwl-runner --outdir /tmp/demo /tmp/demo/prok-annotation-cheetah.cwl /tmp/demo/prok-annotation-cheetah.json

```
I'm not sure what's going on

**Comment by lengjing0519** [comment]
> When I run the running command like this on Mac: `./run_prok_pipeline -i /Users/lengjing/Desktop/712/HW12/GALES_project/GCF_000005845.2_ASM584v2_genomic.fna -od /tmp/demo -v cheetah -rd dbs -t 4` The output is as below:
> 
> ```
> Starting pipeline.  If this is your first time running this pipeline there will be some latency as the necessary Docker images are downloaded. This is a one-time cost.
> Running command: cwl-runner --outdir /tmp/demo /tmp/demo/prok-annotation-cheetah.cwl /tmp/demo/prok-annotation-cheetah.json
> INFO /Users/lengjing/anaconda3/bin/cwl-runner 3.1.20240404144621
> INFO Resolved '/tmp/demo/prok-annotation-cheetah.cwl' to 'file:///tmp/demo/prok-annotation-cheetah.cwl'
> 
> What's Next?
>   1. Sign in to your Docker account → docker login
>   2. View a summary of image vulnerabilities and recommendations → docker scout quickview docker.io/node:alpine
> INFO [workflow ] start
> INFO [workflow ] starting step prodigal
> INFO [step prodigal] start
> INFO [job prodigal] /private/tmp/docker_tmpuhy17gg8$ docker \
>     run \
>     -i \
>     --mount=type=bind,source=/private/tmp/docker_tmpuhy17gg8,target=/sdmbCI \
>     --mount=type=bind,source=/private/tmp/docker_tmp32f30v8w,target=/tmp \
>     --mount=type=bind,source=/Users/lengjing/Desktop/712/HW12/GALES_project/GCF_000005845.2_ASM584v2_genomic.fna,target=/var/lib/cwl/stga7c3fdc0-c221-4638-87a7-355c541f8038/GCF_000005845.2_ASM584v2_genomic.fna,readonly \
>     --workdir=/sdmbCI \
>     --read-only=true \
>     --user=501:20 \
>     --rm \
>     --cidfile=/private/tmp/docker_tmpeu4k361s/20240418084933-250417.cid \
>     --env=TMPDIR=/tmp \
>     --env=HOME=/sdmbCI \
>     jorvis/gales-gce \
>     prodigal \
>     -i \
>     /var/lib/cwl/stga7c3fdc0-c221-4638-87a7-355c541f8038/GCF_000005845.2_ASM584v2_genomic.fna \
>     -f \
>     gff \
>     -o \
>     prodigal.annotation.gff \
>     -a \
>     prodigal.annotation.faa
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> -------------------------------------
> PRODIGAL v2.6.3 [February, 2016]         
> Univ of Tenn / Oak Ridge National Lab
> Doug Hyatt, Loren Hauser, et al.     
> -------------------------------------
> Request:  Single Genome, Phase:  Training
> Reading in the sequence(s) to train...4641652 bp seq created, 50.79 pct GC
> Locating all potential starts and stops...240856 nodes
> Looking for GC bias in different frames...frame bias scores: 1.56 0.18 1.26
> Building initial set of genes to train from...done!
> Creating coding model and scoring nodes...done!
> Examining upstream regions and training starts...done!
> -------------------------------------
> Request:  Single Genome, Phase:  Gene Finding
> Finding genes in sequence #1 (4641652 bp)...done!
> INFO [job prodigal] Max memory used: 411MiB
> INFO [job prodigal] completed success
> INFO [step prodigal] completed success
> INFO [workflow ] starting step barrnap
> INFO [step barrnap] start
> INFO [job barrnap] /private/tmp/docker_tmpa_2uvu8p$ docker \
>     run \
>     -i \
>     --mount=type=bind,source=/private/tmp/docker_tmpa_2uvu8p,target=/sdmbCI \
>     --mount=type=bind,source=/private/tmp/docker_tmphwl816u5,target=/tmp \
>     --mount=type=bind,source=/Users/lengjing/Desktop/712/HW12/GALES_project/GCF_000005845.2_ASM584v2_genomic.fna,target=/var/lib/cwl/stgfc69e62a-a419-4902-92db-5e779e7e0da7/GCF_000005845.2_ASM584v2_genomic.fna,readonly \
>     --workdir=/sdmbCI \
>     --read-only=true \
>     --log-driver=none \
>     --user=501:20 \
>     --rm \
>     --cidfile=/private/tmp/docker_tmp2mrddk7f/20240418085010-990529.cid \
>     --env=TMPDIR=/tmp \
>     --env=HOME=/sdmbCI \
>     jorvis/gales-gce \
>     barrnap \
>     /var/lib/cwl/stgfc69e62a-a419-4902-92db-5e779e7e0da7/GCF_000005845.2_ASM584v2_genomic.fna > /private/tmp/docker_tmpa_2uvu8p/barnapp.gff
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> [12:50:11] This is barrnap 0.7
> [12:50:11] Written by Torsten Seemann <torsten.seemann@gmail.com>
> [12:50:11] Obtained from https://github.com/Victorian-Bioinformatics-Consortium/barrnap
> [12:50:11] Detected operating system: linux
> [12:50:11] Using HMMER binary: /opt/barrnap/bin/../binaries/linux/nhmmer
> [12:50:11] Will use 8 threads
> [12:50:11] Setting evalue cutoff to 1e-06
> [12:50:11] Will tag genes  < 0.8 of expected length.
> [12:50:11] Will reject genes < 0.5 of expected length.
> [12:50:11] Using database: /opt/barrnap/bin/../db/bac.hmm
> [12:50:11] Usage: barrnap <file.fasta>
> WARNING [job barrnap] exited with status: 2
> WARNING [job barrnap] completed permanentFail
> WARNING [step barrnap] completed permanentFail
> INFO [workflow ] completed permanentFail
> {
>     "fasta_files": null,
>     "barrnap_gff_output": {
>         "location": "file:///tmp/demo/barnapp.gff",
>         "basename": "barnapp.gff",
>         "class": "File",
>         "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
>         "size": 0,
>         "path": "/tmp/demo/barnapp.gff"
>     },
>     "aragorn_raw_output": null,
>     "prodigal_annot_file": {
>         "location": "file:///tmp/demo/prodigal.annotation.gff",
>         "basename": "prodigal.annotation.gff",
>         "class": "File",
>         "checksum": "sha1$f55d86eab3f004ededacb8d8a0e6f83bfe3c530d",
>         "size": 1000054,
>         "path": "/tmp/demo/prodigal.annotation.gff"
>     },
>     "prodigal_protein_file": {
>         "location": "file:///tmp/demo/prodigal.annotation.faa",
>         "basename": "prodigal.annotation.faa",
>         "class": "File",
>         "checksum": "sha1$8270e962cb3b5236d84199411127ed8d52d6a7cc",
>         "size": 1943518,
>         "path": "/tmp/demo/prodigal.annotation.faa"
>     },
>     "prodigal_gff3": null,
>     "prodigal_protein_fasta": null,
>     "rapsearch2_m8_files": null,
>     "hmmscan_raw_files": null,
>     "hmmscan_htab_files": null,
>     "tmhmm_raw_files": null,
>     "attributor_files": null,
>     "attributor_output_config": null,
>     "merged_gff3": null
> }WARNING Final process status is permanentFail
> ERROR: Return code 1 when running the following command: cwl-runner --outdir /tmp/demo /tmp/demo/prok-annotation-cheetah.cwl /tmp/demo/prok-annotation-cheetah.json
> ```
> 
> I'm not sure what's going on

**Comment by lengjing0519** [comment]
What's more, I could  run the test.data, so there must be some problems with my data format. But I couldn't figure out the reason. The format of my data is like this:
![截屏2024-04-18 下午9 11 00](https://github.com/jorvis/GALES/assets/82860901/42163c98-f1d3-458c-b394-f2d183a93820)

**Comment by jorvis** [comment]
That format looks fine to me.  Have you tried with another FASTA or by logging into the image interactively and trying that barrnap command which is failing?

**Comment by lengjing0519** [comment]
> That format looks fine to me. Have you tried with another FASTA or by logging into the image interactively and trying that barrnap command which is failing?

I deleted the data in test file and copied my own data into that file and it worked. I couldn't tell what's the real problem.

**Comment by jorvis** [comment]
Ok, please close if it's working for you now.
