### ISSUE TITLE
job hmmscan stuck

### ISSUE THREAD

**Issue by DavidStreid** [jorvis/GALES#7]
I have been running the run_prok_pipeline program, but it stalls on the hmmscan. It's been stuck for about 40 minutes now. Is this expected behavior?

[step hmmscan] start
[job hmmscan] /private/tmp/docker_tmp7IvXQE$ docker \
    run \
    -i \
    --volume=/private/tmp/docker_tmp7IvXQE:/private/var/spool/cwl:rw \
    --volume=/private/var/folders/3b/4r8bn7v959n716gqklzhwj680000gn/T/tmp4iWvqY:/tmp:rw \
    --volume=/PATH/TO/dbs/coding_hmm.lib.bin.h3i:/private/var/lib/cwl/stg1969aaec-9073-4374-81ba-9a3c79d5f9b4/coding_hmm.lib.bin.h3i:ro \
    --volume=/PATH/TO/dbs/coding_hmm.lib.bin.h3m:/private/var/lib/cwl/stg1969aaec-9073-4374-81ba-9a3c79d5f9b4/coding_hmm.lib.bin.h3m:ro \
    --volume=/private/tmp/docker_tmpWgAsy8/prodigal2fasta.faa.part1:/private/var/lib/cwl/stg382e60be-8315-4278-a48f-c6c7a581145e/prodigal2fasta.faa.part1:ro \
    --volume=/PATH/TO/dbs/coding_hmm.lib.bin.h3f:/private/var/lib/cwl/stg1969aaec-9073-4374-81ba-9a3c79d5f9b4/coding_hmm.lib.bin.h3f:ro \
    --volume=/PATH/TO/dbs/coding_hmm.lib.bin.h3p:/private/var/lib/cwl/stg1969aaec-9073-4374-81ba-9a3c79d5f9b4/coding_hmm.lib.bin.h3p:ro \
    --volume=/PATH/TO/dbs/coding_hmm.lib.bin:/private/var/lib/cwl/stg1969aaec-9073-4374-81ba-9a3c79d5f9b4/coding_hmm.lib.bin:ro \
    --workdir=/private/var/spool/cwl \
    --read-only=true \
    --user=501:20 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/private/var/spool/cwl \
    jorvis/gales-gce \
    hmmscan \
    --acc \
    --cut_ga \
    --cpu \
    1 \
    -o \
    hmmscan.out \
    /private/var/lib/cwl/stg1969aaec-9073-4374-81ba-9a3c79d5f9b4/coding_hmm.lib.bin \
    /private/var/lib/cwl/stg382e60be-8315-4278-a48f-c6c7a581145e/prodigal2fasta.faa.part1

**Comment by Ztxfryao009** [comment]
I have same issue and I have been waiting for over 2 hours.

INFO: Output directory is: (./)
INFO: There were 3766 records found in the input file.
INFO: 1 file will be created.
INFO: Most files will have 3766 records in each.
[job split_multifasta] completed success
[step split_multifasta] completed success
[step hmmscan] start
[job hmmscan] /private/tmp/docker_tmpojkhitw9$ docker \
    run \
    -i \
    --volume=/private/tmp/docker_tmpojkhitw9:/private/var/spool/cwl:rw \
    --volume=/private/var/folders/8m/fxmf5vxj73s9vms5djmsgk2r0000gn/T/tmp6tr9hj4w:/tmp:rw \
    --volume=/Users/fengruizhang/GALES/bin/ref/coding_hmm.lib.bin:/private/var/lib/cwl/stg6c41d7c1-6ff1-489c-8937-13692f6adfbc/coding_hmm.lib.bin:ro \
    --volume=/Users/fengruizhang/GALES/bin/ref/coding_hmm.lib.bin.h3f:/private/var/lib/cwl/stg6c41d7c1-6ff1-489c-8937-13692f6adfbc/coding_hmm.lib.bin.h3f:ro \
    --volume=/Users/fengruizhang/GALES/bin/ref/coding_hmm.lib.bin.h3i:/private/var/lib/cwl/stg6c41d7c1-6ff1-489c-8937-13692f6adfbc/coding_hmm.lib.bin.h3i:ro \
    --volume=/Users/fengruizhang/GALES/bin/ref/coding_hmm.lib.bin.h3m:/private/var/lib/cwl/stg6c41d7c1-6ff1-489c-8937-13692f6adfbc/coding_hmm.lib.bin.h3m:ro \
    --volume=/Users/fengruizhang/GALES/bin/ref/coding_hmm.lib.bin.h3p:/private/var/lib/cwl/stg6c41d7c1-6ff1-489c-8937-13692f6adfbc/coding_hmm.lib.bin.h3p:ro \
    --volume=/private/tmp/docker_tmpnu1z2g5j/prodigal2fasta.faa.part1:/private/var/lib/cwl/stgf78dadff-2db8-42b8-9a5f-089551cbd798/prodigal2fasta.faa.part1:ro \
    --workdir=/private/var/spool/cwl \
    --read-only=true \
    --user=501:20 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/private/var/spool/cwl \
    jorvis/gales-gce \
    hmmscan \
    --acc \
    --cut_ga \
    --cpu \
    1 \
    -o \
    hmmscan.out \
    /private/var/lib/cwl/stg6c41d7c1-6ff1-489c-8937-13692f6adfbc/coding_hmm.lib.bin \
    /private/var/lib/cwl/stgf78dadff-2db8-42b8-9a5f-089551cbd798/prodigal2fasta.faa.part1

**Comment by Ztxfryao009** [comment]
3 hrs, final process is success.

**Comment by jorvis** [comment]
Yes, not stalling unless your 'top' output shows that it isn't in running state.  HMM searches are the most computationally intensive of them all so they take a while.  Using the multi-thread option (-t) of the run_prok_pipeline script helps speed things up if your computer has the resources.
